import assert from 'node:assert/strict';
const origin = process.env.TEST_ORIGIN ?? 'http://127.0.0.1:4173';
const testSubnet = 1 + (process.pid % 250);
const request = (path, options = {}) => fetch(`${origin}${path}`, { ...options, headers: { 'cf-connecting-ip': `192.0.${testSubnet}.30`, ...options.headers } });
const home = await request('/');
assert.equal(home.status, 200);
const html = await home.text();
assert.match(html, /Quality brickwork/);
assert.match(html, /property="og:title"/);
assert.match(html, /name="twitter:card"/);
assert.match(html, /name="robots" content="noindex/);
assert.equal(home.headers.get('x-content-type-options'), 'nosniff');
assert.equal(home.headers.get('x-frame-options'), 'DENY');
assert.equal(home.headers.get('cache-control'), 'private, no-store');
assert.equal(home.headers.get('x-powered-by'), null);
const csp = home.headers.get('content-security-policy');
assert.ok(!csp.includes('unsafe-inline') && !csp.includes('unsafe-eval'));
const nonce = csp.match(/'nonce-([^']+)'/)[1];
for (const script of html.matchAll(/<script\b[^>]*>/g)) assert.ok(script[0].includes(`nonce="${nonce}"`), script[0]);
const second = await request('/');
assert.notEqual(second.headers.get('content-security-policy'), csp);
await second.text();
const missing = await request('/does-not-exist');
assert.equal(missing.status, 404);
assert.match(missing.headers.get('x-robots-tag'), /noindex/);
await missing.text();
const robots = await request('/robots.txt');
assert.equal(robots.status, 200);
assert.match(await robots.text(), /Disallow: \//);
const sitemap = await request('/sitemap.xml');
assert.equal(sitemap.status, 200);
assert.ok(!(await sitemap.text()).includes('<loc>'));
const manifest = await request('/manifest.webmanifest');
assert.equal(manifest.status, 200);
assert.equal((await manifest.json()).name, 'Goldkrest Group');
const post = await request('/', { method: 'POST', body: 'test' });
assert.equal(post.status, 405);
assert.equal(post.headers.get('allow'), 'GET, HEAD');
const head = await request('/', { method: 'HEAD' });
assert.equal(head.status, 200);
assert.equal(await head.text(), '');
const pageTitles = new Set();
for (const path of ['/', '/brickwork', '/landscaping', '/pressure-washing', '/contact']) {
  const response = await request(path);
  assert.equal(response.status, 200, path);
  const body = await response.text();
  assert.equal([...body.matchAll(/<h1(?:\s|>)/g)].length, 1, `${path} must have one main heading`);
  assert.match(body, /tel:\+447394633885/);
  assert.match(body, /info@goldkrest.group/);
  const title = body.match(/<title>(.*?)<\/title>/)?.[1];
  assert.ok(title?.includes('Goldkrest Group'), path);
  pageTitles.add(title);
}
assert.equal(pageTitles.size, 5, 'Each page needs a distinct title');
const enquiry = await request('/contact?service=brickwork');
assert.match(await enquiry.text(), /subject=Brickwork%20enquiry/);
const logo = await request('/images/goldkrest-brand.jpeg');
assert.equal(logo.status, 200);
assert.match(logo.headers.get('content-type'), /image\/jpeg/);
await logo.arrayBuffer();
// These invalid/spam requests never reach the email provider.
const contactPost = (body, ip, headers = {}) => request('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://brandonollie.cemseziner.chatgpt.site', 'cf-connecting-ip': ip, ...headers }, body: JSON.stringify(body) });
const crossSite = await contactPost({}, `192.0.${testSubnet}.71`, { Origin: 'https://untrusted.example' });
assert.equal(crossSite.status, 403);
await crossSite.text();
const invalid = await contactPost({ name: 'Test', email: 'invalid', message: 'A test that must not be sent.' }, `192.0.${testSubnet}.72`);
assert.equal(invalid.status, 400);
await invalid.text();
const tooLarge = await contactPost({ message: 'x'.repeat(17000) }, `192.0.${testSubnet}.73`);
assert.equal(tooLarge.status, 413);
await tooLarge.text();
for (let i = 0; i < 3; i++) {
  const malformed = await contactPost({}, `192.0.${testSubnet}.74`);
  assert.equal(malformed.status, 400);
  await malformed.text();
}
const limitedForm = await contactPost({}, `192.0.${testSubnet}.74`);
assert.equal(limitedForm.status, 429);
assert.ok(Number(limitedForm.headers.get('retry-after')) > 0);
const burst = await Promise.all(Array.from({ length: 125 }, () => request('/robots.txt', { headers: { 'cf-connecting-ip': `192.0.${testSubnet}.99` } })));
const statuses = burst.map(r => r.status);
assert.equal(statuses.filter(s => s === 200).length, 120);
assert.equal(statuses.filter(s => s === 429).length, 5);
for (const r of burst.filter(r => r.status === 429)) {
  assert.ok(Number(r.headers.get('retry-after')) > 0);
  assert.match(r.headers.get('x-robots-tag'), /noindex/);
}
await Promise.all(burst.map(r => r.text()));
console.log('HTTP checks passed: metadata, unique CSP nonces, security headers, 404, robots, sitemap, manifest, blocked writes, HEAD, and shared 120/minute limit.');
