import Link from "next/link";
import { ArrowDown, ArrowUpRight, BrickWall, Sprout, Droplets } from "lucide-react";
import { about, services } from "@/lib/content";
import { ContactBand } from "@/components/service-page";
import { pageMetadata } from "@/lib/metadata";
export const metadata = pageMetadata("Brickwork, Landscaping & Restoration", "Goldkrest Group brings 15 years of hands-on experience to brickwork, stone restoration, lime pointing, landscaping and pressure washing.", "/");
const icons = [BrickWall, Sprout, Droplets];
export default function Home() {
  return <>
    <section className="home-hero section-wrap"><div className="hero-copy"><p className="eyebrow"><span className="label-rule" />BRICKWORK, RESTORATION & OUTDOOR SPACES</p><h1>Quality brickwork.<br /><span className="gold-text">Better outdoor spaces.</span></h1><p className="hero-description">From repairing brick and stone to transforming your garden. We bring 15 years of hands-on experience and pride in a job well done.</p><div className="hero-actions"><Link href="/contact" className="button button-gold">Get in touch <ArrowUpRight size={18} aria-hidden="true" /></Link><a href="#our-services" className="text-link">Explore our services <ArrowDown size={16} aria-hidden="true" /></a></div><div className="hero-proof"><span className="proof-number">15<span>+</span></span><span>Years of hands-on<br />experience</span><span className="proof-divider" /><span>Brick & stone specialists.<br />Every job, big or small.</span></div></div><div className="hero-art"><div className="art-corner top-left" /><div className="art-corner bottom-right" /><div className="brand-frame"><img src="/images/projects/masonry-033.webp" alt="Decorative brick paving laid in a geometric pattern on a Goldkrest project" width={1400} height={1050} fetchPriority="high" /></div><span className="art-caption"><span>BRICKWORK & RESTORATION</span><span>THE GOLDKREST STANDARD</span></span></div><a href="#our-services" className="hero-scroll" aria-label="Scroll to our services"><ArrowDown size={19} /></a></section>
    <div className="expertise-strip"><span>BRICKWORK & POINTING</span><span aria-hidden="true">✦</span><span>STONE RESTORATION</span><span aria-hidden="true">✦</span><span>LANDSCAPING</span><span aria-hidden="true">✦</span><span>PRESSURE WASHING</span></div>
    <section id="our-services" className="services-section section-wrap"><div className="section-heading"><div><p className="eyebrow">01 / OUR SERVICES</p><h2>The right skills<br /><span className="muted-heading">for your property.</span></h2></div><p>Specialist restoration. Thoughtful outdoor spaces.<br />The same pride in every project.</p></div><div className="service-cards">{services.map((service, i) => { const Icon = icons[i]; return <Link className="service-card" href={`/${service.slug}`} key={service.slug}><div className="card-top"><Icon size={33} strokeWidth={1} aria-hidden="true" /><span>{service.number}</span></div><div><h3>{service.name}</h3><p>{service.summary}</p></div><span className="card-link">Explore service <ArrowUpRight size={20} aria-hidden="true" /></span></Link>; })}</div></section>
    <section className="about-section section-wrap" id="about"><div className="about-heading"><p className="eyebrow">02 / ABOUT GOLDKREST</p><h2>A heritage of care.<br />A <span className="gold-text">golden</span> standard.</h2><div className="experience-mark"><span>15</span><p>YEARS OF<br />HANDS-ON EXPERIENCE</p></div></div><div className="about-copy"><p>{about}</p><div className="heritage-note"><span className="eyebrow">EXPERIENCE SHAPED ON SITES INCLUDING</span><div><span>St. Paul’s Cathedral</span><span>Houses of Parliament</span></div></div><Link className="text-link" href="/contact">Talk to us about your project <ArrowUpRight size={18} aria-hidden="true" /></Link></div></section>
    <section className="process-section section-wrap"><div className="section-heading"><div><p className="eyebrow">03 / A SIMPLE START</p><h2>From first idea<br />to the finer details.</h2></div><p>Good work starts with understanding<br />what matters to you.</p></div><div className="process-grid"><article><span>01</span><h3>Tell us your plans</h3><p>A repair, a refresh or a new outdoor space. Start with a call or an email.</p></article><article><span>02</span><h3>Find the right approach</h3><p>We discuss the work, the materials and the details that make your project yours.</p></article><article><span>03</span><h3>Bring it to life</h3><p>Careful hands, considered work and pride in the finish. From start to final detail.</p></article></div></section>
    <ContactBand />
  </>;
}
